### ISSUE TITLE
Hack: Faulty usage of Tellor oracle leads multi-million dollar hack

### ISSUE THREAD

**Issue by pmerkleplant** [0xcacti/awesome-oracle-manipulation#2]
See
- https://akshaysrivastav.hashnode.dev/culprit-behind-the-120-million-bonq-attack?utm_source=substack&utm_medium=email
- https://rekt.news/bonq-rekt/?utm_source=substack&utm_medium=email

**Comment by 0xcacti** [comment]
Closing.  Articles added.  Sorry it took so long.  I got lazy.
