### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by max-otc** [0xcacti/awesome-oracle-manipulation#3]
Hi,
When clicking on this link,
[MEV-Boost: Merge ready Flashbots Architecture - The Merge - Ethereum Research](https://hackmd.io/@manifold/S1jRmGIPF)
I get, 
403 Forbidden
You don't have permission to access this resource.
You could head back to home.

**Comment by 0xcacti** [comment]
Yeah, I think that is gone forever.
